apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: jenkins-controller

rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/exec
      - services
      - secrets
      - configmaps
      - persistentvolumeclaims
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch

  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - get
      - list
