apiVersion: apps/v1
kind: Deployment

metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins

spec:
  replicas: 1
  revisionHistoryLimit: 3

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: jenkins

  template:
    metadata:
      labels:
        app: jenkins

    spec:
      serviceAccountName: jenkins

      securityContext:
        fsGroup: 1000

      containers:
        - name: jenkins
          image: abodiaa/jenkins-k8s:1.0
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8080

            - name: agent
              containerPort: 50000

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"

            limits:
              cpu: "1000m"
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home

      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
