spring.application.name=devops-showcase-api

server.address=0.0.0.0
server.port=8080

application.title=CodeAlpha DevOps Showcase API
application.author=Ahmed Diaa Hassan
application.company=CodeAlpha
application.internship=DevOps Internship
application.task=Task 3 - Java Application using Gradle
application.framework=Spring Boot 3
application.buildTool=Gradle
application.version=1.0.0
