Vagrant.configure("2") do |config|

  # Ubuntu 22.04 LTS
  config.vm.box = "ubuntu/jammy64"

  config.vm.hostname = "codealpha-gradle"

  # Private Network
  config.vm.network "private_network", ip: "192.168.56.30"

  # Shared Folder
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "CodeAlpha-Java-Gradle"
    vb.memory = 4096
    vb.cpus = 2
  end

end