Vagrant.configure("2") do |config|

  # =========================
  # Jenkins Controller
  # =========================
  config.vm.define "controller" do |controller|
    controller.vm.box = "ubuntu/focal64"
    controller.vm.hostname = "jenkins-controller"

    controller.vm.network "private_network", ip: "192.168.56.10"

    controller.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # =========================
  # Jenkins Agent
  # =========================
  config.vm.define "agent" do |agent|
    agent.vm.box = "ubuntu/focal64"
    agent.vm.hostname = "jenkins-agent"

    agent.vm.network "private_network", ip: "192.168.56.20"

    agent.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

end